site_name: PSModule Blog
site_url: https://psmodule.github.io/Blog
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Sono
  logo: icon/icon.png
  favicon: icon/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/link
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        primary: black
        accent: green
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        primary: indigo
        accent: green
        icon: material/toggle-switch
        name: Switch to system preference
  icon:
    repo: material/github
    edit: material/pencil
    view: material/eye
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.action.edit

repo_name: PSModule/Blog
repo_url: https://github.com/PSModule/Blog

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
  - social
  - search
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - test

markdown_extensions:
  - toc:
      permalink: true # Adds a link icon to headings
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details # Enables collapsible admonitions

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jedJWCPAhD
      name: PSModule on Discord
    - icon: fontawesome/brands/github
      link: https://github.com/PSModule/
      name: PSModule on GitHub
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

extra_css:
  - stylesheets/extra.css
