name: Publish Blog to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - blog/**
      - mkdocs.yml
      - .github/workflows/Blog.yml

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to checkout the repo
      pages: write   # to deploy to Pages
    steps:
      - uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install mkdocs-material
        run: |
          pip install mkdocs-material

      - name: Publish mkdocs-material project
        run: |
          mkdocs gh-deploy --force
