name: Publish Blog to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - blog/**
      - mkdocs.yml
      - .github/workflows/Blog.yml

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  GH_TOKEN: ${{ github.token }}
permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install mkdocs-material
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-committers-plugin-2

      - name: Publish mkdocs-material project
        run: |
          mkdocs gh-deploy --force
